# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
permalink: date

title: Technology, and espresso.
  #email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Doug Bridgens | Sharing tech on software automation, for more productive development. | 30 years building software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://far-oeuf.com" # the base hostname & protocol for your site, e.g. http://example.com

author: Doug Bridgens

environment: production
google_analytics: G-4X23N63S2J

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# https://github.com/jekyll/minima
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/thisdougb" }
    - { platform: instagram, user_url: "https://instagram.com/far_oeuf" }
    - { platform: twitter, user_url: "https://twitter.com/thisdougb" }

#theme: minima
remote_theme: jekyll/minima

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
